Fix: hydration mismatch on persistent state
foobaragency/foo-state pull request #111
Opened 2022-04-27 13:24 UTC by juan-foobar

## Summary
This PR fixes [the hydration mismatch when using persistent state](https://github.com/foobaragency/foo-state/issues/104).

### Details
On this PR:
- We fixed the bug in the `createReadOnlyHook` function;
- We then refactored the `createHook` function and reused the `createReadOnlyHook` function inside, which brought the fix with it;
- Finally, as a pre-requisite to this fix, we extended the Observable class to save the value used during initialisation.

## How to test

These changes are not easily tested with unit tests because:
- The test cannot be run by changing the browser environment since the environment can not be changed mid-test while the tests are running. We have to choose to set the testing environment to either `jsdom` or `node`. Therefore, we cannot compare the server side rendered vs the client side render on unit tests.
- We tried and avoided hoisting the import of `Person` by using `require`, we did this to avoid running the `createGlobalState` before setting the `localstorage`.
- We are also able to set the `window` to `undefined` mid-test, but that doesn't really help because the check of the window is done once on `createGlobalState` which does not run again.
- The state is global and therefore shared to the component no matter how/where it is rendered.
- We could mock the return of `createGlobalState` to have full control on what to return and when, but that would not make much sense because that is what we want to test... 🙁 

Therefore, we decided to test in "production", well, kind of 😅 The idea was basically test in an app that consumes this library, but we did not want to fo through the whole deployment cycle just to test, so, instead we:
- worked on the changes needed,
- then we built the `foo-state` library by running `yarn build`, 
- once it was built, we went to the `foo-state` folder in the `node_modules` of a project that uses this library and replaced the `lib` and `src` folders with the ones generated in the build from the previous step,
- finally, we ran the project that uses this library and make sure there is no hydration mismatch when using persistent state.

2022-04-28 08:43 UTC, juan-foobar commented
Not sure if this should be a patch or a minor upgrade 🤔 
- It could be considered a patch because it "doesn't change" the current behaviour. There is no API changes either.
- It could, however, be considered a minor upgrade because it potentially changes the output since [react does not guarantee that attribute differences will be patched up in case of mismatches](https://reactjs.org/docs/react-dom.html#hydrate). Also, there are now [stricter hydration errors where hydration mismatches are treated like errors instead of warnings](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#other-breaking-changes).

Thoughts on this?

2022-04-29 10:21 UTC, l-Leniac-l approved these changes
Good job, man!
I recommend you rename the last commit to a semantic release standard to generate a minor upgrade. You could squash all the commits in a single semantic one.

2022-04-29 11:31 UTC, seblondono requested changes

2022-04-29 11:31 UTC, seblondono commented on src/Observable.ts
> +  constructor(private _value: TState) {
Is it intended that you create a private `_value` variable in the class too? If yes, would it be better to keep initialization in the same format?

```
private readonly _initializationValue: TState
private _value: TState

constructor(value: TState) {
  this._value = value
  this._initializationValue = _value
}
```

2022-04-29 11:31 UTC, seblondono commented on src/createHook.ts
> +  const useReadOnlyState = createReadOnlyHook(state$, state => state);
Just for me understanding. You moved all these code to the `createReadOnlyHook` function, right? If so, where does this new subscription do?

```
const subscription = state$.subscribe(observedState => setState(project(observedState)))
```

I am trying to understand why only `setState` was passed before, but now you pass `observedState => setState(project(observedState))`

2022-04-29 13:47 UTC, juan-foobar reviewed
@seblondono thanks for your review! ❤️ 

Let me know if you have any other questions or suggestions :v:

2022-05-02 10:05 UTC, seblondono approved these changes

2022-05-02 12:05 UTC, merged