Support lazy initial state
foobaragency/foo-state pull request #122
Opened 2022-04-29 16:20 UTC by juan-foobar

## Summary

This PR allows us to initialise state with a value set lazily. We do this by providing a callback rather than a value, the callback would then be called and the result of it would be the value used for the initial state.

## How to test

Tests where included to show the support of this feature.

2022-05-02 15:39 UTC, seblondono requested changes

2022-05-02 15:39 UTC, seblondono commented on examples/05_typescript/src/Profile.tsx
> +// We can also do lazy initialization
NIT: Is this comment really needed here?

2022-05-02 15:39 UTC, seblondono commented on src/createReadOnlyHook.ts
> +  const generateProjectedValueCallback = (value: TState) => {
Do you think wrapping this on a `useCallback` would help perf in any way? I think it would not give a huge boost, but would not hurt either.

2022-05-02 15:39 UTC, seblondono commented on src/createReadOnlyHook.ts
> +      const stateValueAfterMountCallback = generateProjectedValueCallback(state$.value)
Are these 2 lines always to written one after the other? I mean, first `generateProjectedValueCallback` and the `setState`. If so, maybe wrap them in another function.

2022-05-02 15:39 UTC, seblondono commented on src/stateInputValueResolver.ts
> +const stateInputValueResolver = <CurrentValue, NextValue = CurrentValue>(
I am not sure if it is a standard to always prefix generic types with a `T`. I still think it would read better and make it double obvious we're talking about types here.

I would like an extra generic value for the type of the states value. I mean, for the `value` itself. This is because, the `currentValue`, the `prevState`, and `nextValue` should all have the same type. And I would also align the naming convention here, are we talking about `value`s or `state`s?

2022-05-02 15:59 UTC, l-Leniac-l commented on src/stateInputValueResolver.ts
> +const stateInputValueResolver = <CurrentValue, NextValue = CurrentValue>(
I agree with you. I would avoid using just `T` since the library already has a standard of using `TState` or `TValue`. But yes, let's make things more transparent on this function.

2022-05-02 16:00 UTC, l-Leniac-l commented on src/createReadOnlyHook.ts
> +      const stateValueAfterMountCallback = generateProjectedValueCallback(state$.value)
I don't think they are. But good input tho.

2022-05-02 16:03 UTC, l-Leniac-l commented on src/createReadOnlyHook.ts
> +  const generateProjectedValueCallback = (value: TState) => {
I don't think it is possible to use a callback here since this is not yet inside the hook. Should we move it inside the hook then? What's the trade-off of doing it?

2022-05-02 16:04 UTC, l-Leniac-l commented on examples/05_typescript/src/Profile.tsx
> +// We can also do lazy initialization
Given this is an example of how to use it, I think it does not harm to have this comment.

2022-05-03 07:09 UTC, seblondono commented on examples/05_typescript/src/Profile.tsx
> +// We can also do lazy initialization
Do you think it would be more complete if this was a JSDoc comment on `createGlobalState`? You don't have to do it now, but since this is also open source, I think that would be a nice addition to the library.

2022-05-03 07:15 UTC, seblondono commented on src/createReadOnlyHook.ts
> +  const generateProjectedValueCallback = (value: TState) => {
Ah I see, thanks for pointing that out. Does `generateProjectedValueCallback` need to live inside of `createReadOnlyHook` then? I just got a bit confused by it, because at the end what we are returning is just a function.

I got another question, tho, what does `project` mean in this case?

2022-05-03 07:19 UTC, seblondono commented on src/createReadOnlyHook.ts
> +  const generateProjectedValueCallback = (value: TState) => {
Let's have a call about this actually, I've got an idea but it's hard to describe here 😅

2022-05-03 07:20 UTC, seblondono commented on src/createReadOnlyHook.ts
> +      const stateValueAfterMountCallback = generateProjectedValueCallback(state$.value)
Well, I don't see any case where you would call `generateProjectedValueCallback` and not use the return to set the `state`... I think they do need to be called one after the other...

2022-05-03 11:39 UTC, juan-foobar commented on examples/05_typescript/src/Profile.tsx
> +// We can also do lazy initialization
Agreed, I have removed the comment and added an [issue to reference this need](https://github.com/foobaragency/foo-state/issues/123).

2022-05-03 11:39 UTC, juan-foobar commented on src/createReadOnlyHook.ts
> +  const generateProjectedValueCallback = (value: TState) => {
After discussing this on a call, the following is what was concluded:
- The `generateProjectedValueCallback` function lives inside the `createReadOnlyHook` because:
  - `generateProjectedValueCallback` is only used by the `createReadOnlyHook` function,
  - the `createReadOnlyHook` should only be called on file loading which limits the `generateProjectedValueCallback` function to be defined once per "global state", and
  - we use the `project` function inside it without having to pass it through the props which in this case is acceptable since it is a parameter and therefore not expected to change within the `createReadOnlyHook` function.
- `generateProjectedValueCallback` is defined once on file load so memoizing the `generateProjectedValueCallback` function should not increase performance.
- `project` stands for _projection_ since it represents a "projection" of the value.

2022-05-03 11:39 UTC, juan-foobar commented on src/createReadOnlyHook.ts
> +      const stateValueAfterMountCallback = generateProjectedValueCallback(state$.value)
Although the state is set using the return value of the `generateProjectedValueCallback` function, the state is set differently. We use the return value of the `generateProjectedValueCallback` function to _initialise_ the state and later use the return value of the `generateProjectedValueCallback` function to _update_ the state.

This should not be abstracted in a function since they are doing different things. If we abstracted setting the state into a function, since it is being used twice, we might be over-abstracting and also opening the opportunity for diverging code which should do the same (generate a callback which resolves in the projected value).

2022-05-03 11:39 UTC, juan-foobar commented on src/stateInputValueResolver.ts
> +const stateInputValueResolver = <CurrentValue, NextValue = CurrentValue>(
>I am not sure if it is a standard to always prefix generic types with a T. I still think it would read better and make it double obvious we're talking about types here.

Thanks for the tip @seblondono, this makes much sense! 👌 I have renamed the types :v:

> I would like an extra generic value for the type of the states value. I mean, for the value itself. This is because, the currentValue, the prevState, and nextValue should all have the same type. And I would also align the naming convention here, are we talking about values or states?

We are talking about the values which represent the different stages of the state. We can have the value of the current state and the value of the next state, whereas the state is specifically what is saved.

When initialising the state the "current state" doesn't yet exist and therefore is `undefined`. In this case, the type of the "current state" and the type of the "next state" are different when initialising the state.

2022-05-03 12:13 UTC, seblondono commented on src/createReadOnlyHook.ts
> +      const stateValueAfterMountCallback = generateProjectedValueCallback(state$.value)
NIT: In line 10 and 11 there are 2 different types of comments. I think they kinda say the same thing, no? Would be cool if you can keep just one and maybe rephrase a bit so it is more clear, maybe something like
```
/**
* explanation
* if A case => B case
* else C case
* /
```

2022-05-03 12:13 UTC, seblondono approved these changes

2022-05-03 12:53 UTC, juan-foobar commented on src/createReadOnlyHook.ts
> +      const stateValueAfterMountCallback = generateProjectedValueCallback(state$.value)
Thanks! I completely missed this, I think it was a merging thing that went wrong or something 😅 

Removed the duplicated unnecessary comment ❤️

2022-05-03 13:03 UTC, merged

2022-05-03 13:07 UTC, kaiserbock commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/foo-state/v/1.2.0)
- [GitHub release](https://github.com/foobaragency/foo-state/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: